#!/bin/bash

readonly type=$1
if [ $type = "chat" ]; then
    cd ./src/app/chatbot
    sh run
elif [ $type = "rec" ]; then
    cd ./src/app/recommend
    sh run
elif [ $type = "front" ]; then
    cd ./src/app/front
    sh run
else
    echo "chat, rec 또는 front 만 입력해주세요"
fi