# chatbot test API
GET http://localhost:8080/test?text=안녕

###

# prompt API (local)
POST http://localhost:8080/prompt
Content-Type: application/json

{
    "state": [],
    "text": "",
    "product_list": ["에스트라 아토베리어365 하이드로 에센스"]
}

###