# chatbot test API
GET http://localhost:8080/test?text=안녕

###

# prompt API (local)
POST http://localhost:8080/prompt
Content-Type: application/json

{
    "state": [],
    "text": "",
    "product_list": ["피지오겔 DMT 페이셜 크림"]
}

###

POST http://localhost:8080/prompt
Content-Type: application/json

{
    "state": [],
    "text": "20대 건성 피부에게 추천하는 기초 로션은 어떤 성분을 가지고 있어?",
    "product_list": []
}